---
title: "Telesaúde - Operação Inverno"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

# Bibliotecas -------------------------------------------------------------
library(pacman)

# Georreferenciamento e mapas
p_load(ggmap)
p_load(sp)
p_load(rgdal)
p_load(hereR)
p_load(geobr)

# Tabelas, Ferramentas estatísticas,
p_load(directlabels)
p_load(esquisse)
p_load(obAnalytics)
p_load(DescTools)
p_load(kableExtra)
p_load(RColorBrewer)
p_load(scales)
p_load(reactable)

# Dashboards e HTML
p_load(htmlwidgets)
p_load(highcharter)
p_load(leaflet)
p_load(htmltools)
p_load(fontawesome)

# Data wrangling
p_load(collapse)
p_load(here)
p_load(tictoc)
p_load(patchwork)
p_load(janitor)
p_load(glue)

# Próprios
p_load(cid10)
p_load(msrpack)

# Leitura
p_load(openxlsx)
p_load(readxl)
p_load(WriteXLS)
p_load(ggthemes)
p_load(googlesheets4)
p_load(vroom)

# Transformação e análise de dados
p_load(caret)
p_load(zoo)
p_load(tidyverse)
p_load(lubridate)

# Ajustes locais ----------------------------------------------------------

set_key(api_key = "tfgapuFbaa8rSY0QS_dbZj9d8qmdeKiXFHl2L39b-FY") # Api HERE
Sys.setenv(TZ="America/Recife")
options(tz="America/Recife")
Sys.getenv("TZ")
options(scipen = 999999)
Sys.setlocale("LC_TIME", "pt_BR")




# Carregamentos iniciais --------------------------------------------------
# Arquivos gerados pelo script moniramento.r
# 


internados <- read_rds(file = "../bin/internados.rds")
op_inverno <- read_rds(file = "../bin/op_inverno.rds")
hospitais_poa <- read_rds(file = "/Users/marciorodrigues/Dropbox/Coding/R/data/cnes/bin/hospitais_poa.rds")


# Bancos auxiliares ------------------------------------------------------

pediatria <- internados %>% 
  filter(grepl("PEDIAT", tipoleito))

uti <- internados %>% 
  filter(grepl("UTI", tipoleito))



```


Row
-----------------------------------------------------------------------

### Total de Pacientes

```{r}
htmltools::tagList(fontawesome::fa_html_dependency())
valueBox(
  value = glue("{nrow(internados)} pacientes"), 
  caption = "Internados por CIDs Respiratórios",
  icon = "fas fa-hospital-user")


```

### Pacientes Pediátricos

```{r}



valueBox(
  value = glue("{nrow(pediatria)} pediátricos"), 
  caption = "Internados por CIDs Respiratórios",
  icon = "fa-baby")


```


### Terapia intensiva

```{r}



valueBox(
  value = glue("{nrow(uti)} na UTI"), 
  caption = "Internados por CIDs Respiratórios", 
  color = "info",
  icon = "fa-procedures")


```


Row
-----------------------------------------------------------------------

```{r, include=FALSE}

ultima_internacao <- format.POSIXct(max(internados$datahorainternacao), "%A, %d de %B de %Y, as %H:%M:%Sh")



```


### Monitoramento da Operação Inverno

Este Dashboard é para consulta dos pacientes internados por cids respiratórios nesse momento. É um auxilio as equipes de monitoramento do **Telesaúde** de Porto Alegre.

* Última internação: `r ultima_internacao`




### Distribuição por idade

```{r}
internados %>% 
  group_by(idade) %>% 
  tally() %>% 
  ggplot(aes(x = idade, y = n)) + geom_col() +
  ylab("Quantidade de Paciente Internados") + 
  xlab("Idade dos pacientes")
```


### Hospitais envolvidos

```{r}

int_hosp <- left_join(internados, hospitais_poa, by = c("executante" = "no_fantasia")) %>% 
  select(executante, nu_latitude, nu_longitude) %>% 
  group_by(executante, nu_latitude, nu_longitude) %>% 
  tally() %>% 
  mutate(
    legenda = glue(.sep = "<br/>", "<b>{executante}</b>", "Quantidade de pacientes: {n} <br/>")
    )

leaflet(data = int_hosp) %>% 
  addTiles() %>% 
  addCircleMarkers(
    lng = ~nu_longitude, 
    lat = ~nu_latitude, 
    radius = ~log(n, base = 1.5), 
    popup = ~as.character(legenda),
    label =~as.character(executante) 
    ) 


```

Column {data-width=350}
-----------------------------------------------------------------------

### Pacientes internados no momento

```{r}


internados %>% 
  select(datahorainternacao, protocologerint, tipoleito, carater, idade, sexo, executante) %>% 
  mutate(
    datahorainternacao = date(datahorainternacao)
  ) %>% 
reactable(
  groupBy = "executante", 
  columns = list(
    executante = colDef(name = "Hospital Executante", minWidth = 600, align = "left"),
    datahorainternacao = colDef(name = "Internação", minWidth = 110),
    protocologerint = colDef(name = "Gerint", minWidth = 120),
    tipoleito = colDef(name = "Tipo de Leito", minWidth = 150),
    carater = colDef(name = "Carater", minWidth = 120),
    idade = colDef(name = "Idade", minWidth = 70, align = "center"),
    sexo = colDef(name = "Sexo", minWidth = 100),
    datahorainternacao = colDef(name = "Data da Internação", minWidth = 100),
    datahorainternacao = colDef(name = "Data da Internação", minWidth = 100)
  ), 
  sortable = TRUE, 
  resizable = TRUE, 
  filterable = TRUE, 
  showPageSizeOptions = TRUE, 
  defaultPageSize = 25, 
  highlight = TRUE,
  striped = TRUE, 
  showSortable = TRUE,defaultColDef = colDef(align = "center")
  
  
)

```

